DOMAIN = "solis_cloud_control"

CONF_INVERTER_SN = "inverter_sn"

API_BASE_URL = "https://www.soliscloud.com:13333"
API_READ_ENDPOINT = "/v2/api/atRead"
API_READ_BATCH_ENDPOINT = "/v2/api/atReadBatch"
API_CONTROL_ENDPOINT = "/v2/api/control"
API_TIMEOUT_SECONDS = 10
API_RETRY_COUNT = 3  # initial attempt + 2 retries
API_RETRY_DELAY_SECONDS = 5
API_CONCURRENT_REQUESTS = 2

CID_STORAGE_MODE = 636
CID_CHARGE_SLOT1_TIME = 5946
CID_CHARGE_SLOT1_CURRENT = 5948
CID_CHARGE_SLOT1_SOC = 5928
CID_DISCHARGE_SLOT1_TIME = 5964
CID_DISCHARGE_SLOT1_CURRENT = 5967
CID_DISCHARGE_SLOT1_SOC = 5965
