name: Release

on:
  push:
    tags:
      - "v*"

env:
  COMPONENT_NAME: solis_cloud_control

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Set version number
        run: |
          version=${GITHUB_REF_NAME#v}
          yq e -P -o=json \
            -i ".version = \"${version}\"" \
            "${{ github.workspace }}/custom_components/${{ env.COMPONENT_NAME }}/manifest.json"

      - name: Zip ${{ env.COMPONENT_NAME }} directory
        run: |
          cd "${{ github.workspace }}/custom_components/${{ env.COMPONENT_NAME }}"
          zip ${{ env.COMPONENT_NAME }}.zip -r ./

      - uses: requarks/changelog-action@v1
        id: changelog
        with:
          token: ${{ github.token }}
          tag: ${{ github.ref_name }}
          useGitmojis: false

      - uses: softprops/action-gh-release@v2
        with:
          files: ${{ github.workspace }}/custom_components/${{ env.COMPONENT_NAME }}/${{ env.COMPONENT_NAME }}.zip
          body: ${{ steps.changelog.outputs.changes }}
          prerelease: ${{ contains(github.ref_name, '-alpha') || contains(github.ref_name, '-beta') || contains(github.ref_name, '-rc') }}
