name: Stale

on:
  schedule:
    - cron: "30 1 * * *" #  1:30 AM UTC every day
  workflow_dispatch:

jobs:
  stale:
    runs-on: ubuntu-latest

    permissions:
      issues: write
      pull-requests: write

    steps:
      - uses: actions/stale@v9
        with:
          # Issue settings
          days-before-stale: 30
          days-before-close: 7
          stale-issue-message: "This issue has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs. Thank you for your contributions."
          close-issue-message: "This issue was closed because it has been stale for 7 days with no activity."

          # PR settings
          days-before-pr-stale: 30
          days-before-pr-close: 7
          stale-pr-message: "This pull request has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs. Thank you for your contributions."
          close-pr-message: "This pull request was closed because it has been stale for 7 days with no activity."
